version: "2.1"

services:
  infinitude:
    container_name: infinitude
    hostname: infinitude
    image: nebulous/infinitude:latest
    entrypoint: "morbo -v /infinitude/infinitude"
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./:/infinitude/
    environment:
      - APP_SECRET=Pogotudinal
      - PASS_REQS=300
      - SERIAL_TTY=/dev/ttyUSB0
      - MOJO_MODE=development
      - MOJO_LOG_COLOR=1
      - MOJO_LOG_LEVEL=debug
      - SCAN_THERMOSTAT=1
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
